[workspace]
members = [
    "mmio",
    "boot",
    "shared",
]

[profile.release]
opt-level = 's'  # Controls the --opt-level the compiler builds with
debug = true   # Controls whether the compiler passes `-g`
