[workspace]
resolver= "2"
members = [
    "usb",
    "mmio",
    "shared",
    "init",
    "kernel",
    "boot",
]

[profile.release]
opt-level = 's'  # Controls the --opt-level the compiler builds with
debug = true   # Controls whether the compiler passes `-g`
