[package]
name = "aos-kernel"
version = "0.1.0"
authors = ["Alban Seurat <alban.seurat@me.com>"]
edition = "2018"

[dependencies]
r0 = "0.2.2"
cortex-a = "2.3.1"
panic-abort = "0.3.1"

[package.metadata.cargo-xbuild]
sysroot_path = "../xbuild_sysroot"