[package]
name = "aos-remote"
version = "0.1.0"
authors = ["Alban Seurat <alban.seurat@me.com>"]
edition = "2018"

[dependencies]
cortex-a = { git = "https://github.com/AlbanSeurat/cortex-a", branch = "elr_el1" }
register = "0.3.3"

[package.metadata.cargo-xbuild]
sysroot_path = "../xbuild_sysroot"